services:
      app :
        build : .
        container_name : ai_app
        ports : 
        - "8000:8000"
        on_depends : db
        restart : always    

      db:
       image : mysql:latest 
       container_name : mysql_app
       ports : 
       - "3306:3306"
       volumes : 
       - mysql_db:/var/lib/mysql
       restart : always  
       environment : 
       - MYSQL_USER=root
       - MYSQL_ROOT_PASSWORD=kartik@25
       - MYSQL_DATABASE=ai_english


       mongo_db:
            image : mongo:latest 
            container_name : mongo_app  
            ports :  
            - "27017:27017"
            restart : always 
            volumes : 
            - mongodb_db:/data/db  
            


volumes:
      mysql_db
      mongodb_db